apiVersion: v2
description: Helm Chart for example-voting-app required infrastructure
name: example-voting-app-infra
keywords:
  - codefresh
  - kubernetes
  - example-voting-app
  - infrastructure
version: 1.2.0
sources:
  - https://github.com/salesdemocf/configs/charts/example-voting-app-infra
maintainers:
  - name: Dustin Van Buskirk
    email: dustin@codefresh.io
dependencies:
  - name: postgresql
    version: 18.1.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - db
  - name: redis
    version: 24.0.8
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - queue
